export const SET_TOAST_MSG = 'SET_TOAST_MSG'

export const SET_USER_TOKEN = 'SET_USER_TOKEN'

export const SET_USER_INFO_ID = 'SET_USER_INFO_ID'

export const SET_INFO_FLAG = 'SET_INFO_FLAG'

export const SET_HAS_ZFMM = 'SET_HAS_ZFMM'

export const SET_USER_WALLET_MONEY = 'SET_USER_WALLET_MONEY'

export const SET_FORGET_PWD = 'SET_FORGET_PWD'

export const SET_CATEGORY_ID = 'SET_CATEGORY_ID'

export const SET_GOODSID = 'SET_GOODSID'

export const SET_HIDDENHTAB = 'SET_HIDDENHTAB'

export const SET_HIDDENFTAB = 'SET_HIDDENFTAB'

export const SET_PROGRAMTYPE = 'SET_PROGRAMTYPE'

export const SET_OPENID = 'SET_OPENID'

export const SET_USER_MOBILE = 'SET_USER_MOBILE'

export const SET_ORDERNO = 'SET_ORDERNO'

export const SET_RED_PACKET_MONEY = 'SET_RED_PACKET_MONEY'

export const SET_USER_WALLET_ID = 'SET_USER_WALLET_ID'

export const SET_ORDER_GOODS_IDS = 'SET_ORDER_GOODS_IDS'

export const SET_THEMEID = 'SET_THEMEID'

export const SET_GOODSJSON = 'SET_GOODSJSON'

export const SET_VISIT_BOOK_RETEMPID = 'SET_VISIT_BOOK_RETEMPID'

export const SET_WXUNIONID = 'SET_WXUNIONID'

export const SET_REFERRALCODE = 'SET_REFERRALCODE'

export const SET_ISSUPERVIP = 'SET_ISSUPERVIP'

export const SET_SHARE_THUMBS = 'SET_SHARE_THUMBS'

export const SET_INVITE_TITLE = 'SET_INVITE_TITLE'

export const SET_INVITE_CONTENT = 'SET_INVITE_CONTENT'

export const SET_USERAVATAR = 'SET_USERAVATAR'

export const SET_USERNICKNAME = 'SET_USERNICKNAME'